server:
  port: 8899
  servlet:
    context-path: /ipprefered #请求路径，可以自定义
  tomcat:
    max-swallow-size: -1
  shutdown: graceful

spring:
  datasource:
    url: jdbc:sqlite:/app/db/db.sqlite #linux jdbc:sqlite:/app/db/db.sqlite  windows：jdbc:sqlite:D:/db.sqlite
    driver-class-name: org.sqlite.JDBC
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  sql:
    init:
      mode: always #第一次启动设置为always，后面都设置为never
      continue-on-error: true
      data-locations: classpath:db/init.sql
      schema-locations: classpath:db/create.sql

mybatis:
  type-aliases-package: com.bienao.ippreferred.entity
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log.xml

cf:
  email: airportypgt@yandex.com #cloudflare账号
  token: sA1iEyvpIUBzMS5ykUq6J1rcPA2nnw10AsFZhlUy #cloudflare令牌
  zone: cdn1.kitchen.cf:2082:true|cdn2.kitchen.cf:2082:true|cnd3.kitchen.cf:2082:false|cdn4.kitchen.cf:2082:false|cdn5.kitchen.cf:2082:false #cdn1.xxx.xxx:2082:false，域名：端口：是否开启tls(true/false)，多个用|隔开

wxpusher: #消息推送 https://wxpusher.zjiecode.com/admin/
  token: xxx #wxpusher 令牌
  uid: xxx #wxpusher推送用户id

threadCount: 50 #测试线程数，不填默认50
enablePushNormal: false #填 true 域名定时测试都会推送，填 false 不推送，5分钟一次，建议关闭
enablePushInvalid: true #填 true 域名测试失败才会推送，填 false 不推送

scheduled:
  testZone: 0 0/5 * * * ? #域名定时测试，默认配置5分钟一次
  ipstest: 0 0 12 ? * Mon #筛选可用CDN，默认配置每周一执行一次，无需执行太频繁
  goodipstest: 0 0 3 * * ? #过滤不可用CDN，默认配置每天三点执行一次
